Write symbol table
mdsteele/rust-ar pull request #17
Opened 2020-07-11 15:16 UTC by bjorn3

This means that it is no longer necessary to run `ranlib` afterwards. This PR also contains various cleanups. This is a breaking change.

# TODO

* [ ] Implement symbol table writing for BSD style archives.

2020-09-16 15:00 UTC, bjorn3 commented
Ping @mdsteele

2020-09-17 23:42 UTC, mdsteele requested changes
Thanks for doing this work.  It's a little hard to review all at once, but I have some initial comments.

Just to check, since the code has moved around: are all the previously existing tests still there?

2020-09-17 23:42 UTC, mdsteele commented on src/lib.rs
> +    BSD,
Looking at https://rust-lang.github.io/api-guidelines/naming.html it looks like preferred style would be to name these `Bsd`, `Gnu`, and `Gnu64Bit`.  Unfortunately, the existing `Variant` enum above is already violating this rule, but if this commit is going to break API compatibility, then maybe this is a good opportunity to fix that too.

2020-09-17 23:42 UTC, mdsteele commented on src/lib.rs
> +//! let mut builder = Builder::new(File::create("foo.a").unwrap(), BTreeMap::new()).unwrap();
It feels a little awkward to have to construct and supply an empty map for users that don't need a symbol table.  Perhaps we could have separate `new` and `new_with_symbol_table` constructors?  (Or whatever you want to call them.)

2020-09-17 23:42 UTC, mdsteele commented on src/write.rs
> +        symbol_table: BTreeMap<Vec<u8>, Vec<Vec<u8>>>,
It's not immediately obvious to me what the various `Vec`s represent here; could you expand the doc comment a bit to explain?

2020-09-17 23:42 UTC, mdsteele commented on src/write.rs
> +        deterministic: bool,
Ditto, it would help to expand the doc comment for `new` to briefly explain what these new parameters are for (possibly with a reference back to the struct doc comment which seems to have a more complete explanation already).

2020-09-18 10:32 UTC, bjorn3 commented
> Just to check, since the code has moved around: are all the previously existing tests still there?

Yes

The symbol table writing for BSD is incorrect. @GregBowyer said they will investigate, but hasn't had time yet. I have changed `new_with_symbol_table` to private for now.

2022-05-18 06:01 UTC, messense commented
I need this functionality in a project, any progress on this? Any plan to move forward? Thanks!

2022-05-18 06:07 UTC, bjorn3 commented
This PR doesn't work on macOS. I'm planning to instead rewrite LLVM's archive writer in rust and publish it as separate project. That is the easiest way to be certain it works on all platforms supported by LLVM.

2023-07-27 18:02 UTC, bjorn3 commented
I ported LLVM's archive writer to rust in https://github.com/rust-lang/ar_archive_writer instead.

2023-07-27 18:02 UTC, closed without merging